export interface DogBreed {
  id: string
  name: string
  image: string
  description: string
  traits: {
    energy_level: "low" | "medium" | "high"
    size: "small" | "medium" | "large"
    grooming_needs: "minimal" | "moderate" | "high"
    good_with_children: boolean
    good_with_pets: boolean
    hypoallergenic: boolean
    apartment_friendly: boolean
    experience_needed: "beginner" | "intermediate" | "advanced"
    temperament: string[]
  }
  care_info: {
    exercise_needs: string
    grooming_tips: string
    health_considerations: string
  }
}

export const dogBreeds: DogBreed[] = [
  {
    id: "golden_retriever",
    name: "Golden Retriever",
    image: "https://images.dog.ceo/breeds/retriever-golden/n02099601_1024.jpg",
    description:
      "Friendly, intelligent, and devoted. Golden Retrievers are among the most popular dog breeds for families.",
    traits: {
      energy_level: "high",
      size: "large",
      grooming_needs: "moderate",
      good_with_children: true,
      good_with_pets: true,
      hypoallergenic: false,
      apartment_friendly: false,
      experience_needed: "beginner",
      temperament: ["playful", "social", "calm"],
    },
    care_info: {
      exercise_needs: "Needs 1-2 hours of exercise daily including walks, fetch, and swimming",
      grooming_tips: "Brush 2-3 times per week, daily during shedding seasons",
      health_considerations: "Prone to hip dysplasia, eye conditions, and heart problems",
    },
  },
  {
    id: "french_bulldog",
    name: "French Bulldog",
    image: "https://images.dog.ceo/breeds/bulldog-french/n02108915_5733.jpg",
    description: "Adaptable, playful, and smart. French Bulldogs are perfect for city living and smaller spaces.",
    traits: {
      energy_level: "low",
      size: "small",
      grooming_needs: "minimal",
      good_with_children: true,
      good_with_pets: true,
      hypoallergenic: false,
      apartment_friendly: true,
      experience_needed: "beginner",
      temperament: ["playful", "calm", "social"],
    },
    care_info: {
      exercise_needs: "Short walks and indoor play, avoid overexertion",
      grooming_tips: "Weekly brushing and regular face cleaning",
      health_considerations: "Breathing issues, overheating, and spinal problems",
    },
  },
  {
    id: "poodle",
    name: "Standard Poodle",
    image: "https://images.dog.ceo/breeds/poodle-standard/n02113799_4470.jpg",
    description: "Intelligent, active, and hypoallergenic. Poodles are excellent for active families with allergies.",
    traits: {
      energy_level: "high",
      size: "large",
      grooming_needs: "high",
      good_with_children: true,
      good_with_pets: true,
      hypoallergenic: true,
      apartment_friendly: false,
      experience_needed: "intermediate",
      temperament: ["playful", "social", "independent"],
    },
    care_info: {
      exercise_needs: "High exercise needs including mental stimulation",
      grooming_tips: "Professional grooming every 6-8 weeks, daily brushing",
      health_considerations: "Hip dysplasia, eye problems, and bloat",
    },
  },
  {
    id: "cavalier_king_charles",
    name: "Cavalier King Charles Spaniel",
    image: "https://images.dog.ceo/breeds/spaniel-cavalier/n02099601_1024.jpg",
    description: "Gentle, friendly, and graceful. Perfect lap dogs that adapt well to any living situation.",
    traits: {
      energy_level: "medium",
      size: "small",
      grooming_needs: "moderate",
      good_with_children: true,
      good_with_pets: true,
      hypoallergenic: false,
      apartment_friendly: true,
      experience_needed: "beginner",
      temperament: ["calm", "social", "playful"],
    },
    care_info: {
      exercise_needs: "Moderate exercise with daily walks and playtime",
      grooming_tips: "Brush 2-3 times per week, regular ear cleaning",
      health_considerations: "Heart conditions, eye problems, and neurological issues",
    },
  },
  {
    id: "german_shepherd",
    name: "German Shepherd",
    image: "https://images.dog.ceo/breeds/germanshepherd/n02106662_1031.jpg",
    description: "Confident, courageous, and smart. German Shepherds are extremely versatile working dogs.",
    traits: {
      energy_level: "high",
      size: "large",
      grooming_needs: "moderate",
      good_with_children: true,
      good_with_pets: false,
      hypoallergenic: false,
      apartment_friendly: false,
      experience_needed: "advanced",
      temperament: ["protective", "independent", "playful"],
    },
    care_info: {
      exercise_needs: "High exercise and mental stimulation requirements",
      grooming_tips: "Brush several times per week, daily during shedding",
      health_considerations: "Hip and elbow dysplasia, bloat, and degenerative myelopathy",
    },
  },
  {
    id: "shih_tzu",
    name: "Shih Tzu",
    image: "https://images.dog.ceo/breeds/shihtzu/n02086240_6840.jpg",
    description: "Affectionate, playful, and outgoing. Shih Tzus are bred to be companions and house pets.",
    traits: {
      energy_level: "low",
      size: "small",
      grooming_needs: "high",
      good_with_children: true,
      good_with_pets: true,
      hypoallergenic: true,
      apartment_friendly: true,
      experience_needed: "beginner",
      temperament: ["calm", "social", "playful"],
    },
    care_info: {
      exercise_needs: "Light exercise with short walks and indoor play",
      grooming_tips: "Daily brushing and professional grooming every 6-8 weeks",
      health_considerations: "Breathing problems, eye issues, and hip dysplasia",
    },
  },
  {
    id: "labrador_retriever",
    name: "Labrador Retriever",
    image: "https://images.dog.ceo/breeds/labrador/n02099712_6901.jpg",
    description: "Friendly, outgoing, and high-spirited. Labradors are excellent family dogs and great with children.",
    traits: {
      energy_level: "high",
      size: "large",
      grooming_needs: "moderate",
      good_with_children: true,
      good_with_pets: true,
      hypoallergenic: false,
      apartment_friendly: false,
      experience_needed: "beginner",
      temperament: ["playful", "social", "calm"],
    },
    care_info: {
      exercise_needs: "Needs 1-2 hours of exercise daily including walks, fetch, and swimming",
      grooming_tips: "Brush 2-3 times per week, daily during shedding seasons",
      health_considerations: "Prone to hip dysplasia, eye conditions, and heart problems",
    },
  },
  {
    id: "bulldog",
    name: "Bulldog",
    image: "https://images.dog.ceo/breeds/bulldog-english/jager-1.jpg",
    description: "Calm, courageous, and friendly. Bulldogs are known for their wrinkled face and pushed-in nose.",
    traits: {
      energy_level: "low",
      size: "medium",
      grooming_needs: "minimal",
      good_with_children: true,
      good_with_pets: true,
      hypoallergenic: false,
      apartment_friendly: true,
      experience_needed: "beginner",
      temperament: ["calm", "social", "playful"],
    },
    care_info: {
      exercise_needs: "Short walks and indoor play, avoid overexertion",
      grooming_tips: "Weekly brushing and regular face cleaning",
      health_considerations: "Breathing issues, overheating, and spinal problems",
    },
  },
  {
    id: "beagle",
    name: "Beagle",
    image: "https://images.dog.ceo/breeds/beagle/n02088364_11136.jpg",
    description: "Curious, friendly, and merry. Beagles are great family pets and excellent with children.",
    traits: {
      energy_level: "medium",
      size: "small",
      grooming_needs: "minimal",
      good_with_children: true,
      good_with_pets: true,
      hypoallergenic: false,
      apartment_friendly: true,
      experience_needed: "beginner",
      temperament: ["playful", "social", "independent"],
    },
    care_info: {
      exercise_needs: "Moderate exercise with daily walks and playtime",
      grooming_tips: "Brush 2-3 times per week, regular ear cleaning",
      health_considerations: "Heart conditions, eye problems, and neurological issues",
    },
  },
  {
    id: "dachshund",
    name: "Dachshund",
    image: "https://images.dog.ceo/breeds/dachshund/dachshund-1.jpg",
    description: "Lively, courageous, and devoted. Dachshunds are known for their long body and short legs.",
    traits: {
      energy_level: "medium",
      size: "small",
      grooming_needs: "minimal",
      good_with_children: true,
      good_with_pets: true,
      hypoallergenic: false,
      apartment_friendly: true,
      experience_needed: "beginner",
      temperament: ["playful", "social", "independent"],
    },
    care_info: {
      exercise_needs: "Moderate exercise with daily walks and playtime",
      grooming_tips: "Brush 2-3 times per week, regular ear cleaning",
      health_considerations: "Heart conditions, eye problems, and neurological issues",
    },
  },
  {
    id: "siberian_husky",
    name: "Siberian Husky",
    image: "https://images.dog.ceo/breeds/husky/n02110185_1469.jpg",
    description: "Energetic, athletic, and intelligent. Huskies are known for their striking appearance and friendly nature.",
    traits: {
      energy_level: "high",
      size: "medium",
      grooming_needs: "high",
      good_with_children: true,
      good_with_pets: true,
      hypoallergenic: false,
      apartment_friendly: false,
      experience_needed: "advanced",
      temperament: ["playful", "social", "independent"],
    },
    care_info: {
      exercise_needs: "High exercise and mental stimulation requirements",
      grooming_tips: "Brush several times per week, daily during shedding",
      health_considerations: "Hip and elbow dysplasia, bloat, and degenerative myelopathy",
    },
  },
  {
    id: "rottweiler",
    name: "Rottweiler",
    image: "https://images.dog.ceo/breeds/rottweiler/n02106550_7290.jpg",
    description: "Loyal, confident, and courageous. Rottweilers are known for their strength and protective nature.",
    traits: {
      energy_level: "high",
      size: "large",
      grooming_needs: "minimal",
      good_with_children: true,
      good_with_pets: false,
      hypoallergenic: false,
      apartment_friendly: false,
      experience_needed: "advanced",
      temperament: ["protective", "independent", "playful"],
    },
    care_info: {
      exercise_needs: "High exercise and mental stimulation requirements",
      grooming_tips: "Brush several times per week, daily during shedding",
      health_considerations: "Hip and elbow dysplasia, bloat, and degenerative myelopathy",
    },
  },
  {
    id: "yorkshire_terrier",
    name: "Yorkshire Terrier",
    image: "https://images.dog.ceo/breeds/terrier-yorkshire/n02094433_2315.jpg",
    description: "Bold, confident, and intelligent. Yorkies are small but mighty, with a big personality.",
    traits: {
      energy_level: "medium",
      size: "small",
      grooming_needs: "high",
      good_with_children: true,
      good_with_pets: true,
      hypoallergenic: true,
      apartment_friendly: true,
      experience_needed: "beginner",
      temperament: ["playful", "social", "independent"],
    },
    care_info: {
      exercise_needs: "Moderate exercise with daily walks and playtime",
      grooming_tips: "Daily brushing and professional grooming every 6-8 weeks",
      health_considerations: "Breathing problems, eye issues, and hip dysplasia",
    },
  },
  {
    id: "boxer",
    name: "Boxer",
    image: "https://images.dog.ceo/breeds/boxer/n02108089_1031.jpg",
    description: "Playful, patient, and energetic. Boxers are great family dogs and excellent with children.",
    traits: {
      energy_level: "high",
      size: "large",
      grooming_needs: "minimal",
      good_with_children: true,
      good_with_pets: true,
      hypoallergenic: false,
      apartment_friendly: false,
      experience_needed: "intermediate",
      temperament: ["playful", "social", "calm"],
    },
    care_info: {
      exercise_needs: "High exercise and mental stimulation requirements",
      grooming_tips: "Brush several times per week, daily during shedding",
      health_considerations: "Hip and elbow dysplasia, bloat, and degenerative myelopathy",
    },
  },
  {
    id: "chihuahua",
    name: "Chihuahua",
    image: "https://images.dog.ceo/breeds/chihuahua/n02085620_4157.jpg",
    description: "Lively, alert, and devoted. Chihuahuas are the smallest dog breed and have a big personality.",
    traits: {
      energy_level: "medium",
      size: "small",
      grooming_needs: "minimal",
      good_with_children: true,
      good_with_pets: true,
      hypoallergenic: false,
      apartment_friendly: true,
      experience_needed: "beginner",
      temperament: ["playful", "social", "independent"],
    },
    care_info: {
      exercise_needs: "Moderate exercise with daily walks and playtime",
      grooming_tips: "Brush 2-3 times per week, regular ear cleaning",
      health_considerations: "Heart conditions, eye problems, and neurological issues",
    },
  },
  {
    id: "great_dane",
    name: "Great Dane",
    image: "https://images.dog.ceo/breeds/dane-great/n02109047_286.jpg",
    description: "Gentle, friendly, and patient. Great Danes are known for their massive size and gentle nature.",
    traits: {
      energy_level: "medium",
      size: "large",
      grooming_needs: "minimal",
      good_with_children: true,
      good_with_pets: true,
      hypoallergenic: false,
      apartment_friendly: false,
      experience_needed: "intermediate",
      temperament: ["calm", "social", "playful"],
    },
    care_info: {
      exercise_needs: "Moderate exercise with daily walks and playtime",
      grooming_tips: "Brush several times per week, daily during shedding",
      health_considerations: "Hip and elbow dysplasia, bloat, and degenerative myelopathy",
    },
  },
  {
    id: "border_collie",
    name: "Border Collie",
    image: "https://images.dog.ceo/breeds/collie-border/n02106166_1031.jpg",
    description: "Intelligent, energetic, and hardworking. Border Collies are known for their incredible herding abilities.",
    traits: {
      energy_level: "high",
      size: "medium",
      grooming_needs: "moderate",
      good_with_children: true,
      good_with_pets: true,
      hypoallergenic: false,
      apartment_friendly: false,
      experience_needed: "advanced",
      temperament: ["intelligent", "energetic", "loyal"],
    },
    care_info: {
      exercise_needs: "Needs extensive daily exercise and mental stimulation",
      grooming_tips: "Brush 2-3 times per week, more during shedding seasons",
      health_considerations: "Hip dysplasia, eye conditions, and epilepsy",
    },
  },
  {
    id: "samoyed",
    name: "Samoyed",
    image: "https://images.dog.ceo/breeds/samoyed/n02111889_4470.jpg",
    description: "Friendly, gentle, and adaptable. Samoyeds are known for their beautiful white coat and smiling face.",
    traits: {
      energy_level: "high",
      size: "medium",
      grooming_needs: "high",
      good_with_children: true,
      good_with_pets: true,
      hypoallergenic: false,
      apartment_friendly: false,
      experience_needed: "intermediate",
      temperament: ["friendly", "gentle", "playful"],
    },
    care_info: {
      exercise_needs: "Daily exercise and mental stimulation required",
      grooming_tips: "Daily brushing and regular professional grooming",
      health_considerations: "Hip dysplasia, eye conditions, and heart problems",
    },
  },
  {
    id: "bernese_mountain",
    name: "Bernese Mountain Dog",
    image: "https://images.dog.ceo/breeds/mountain-bernese/n02107683_1031.jpg",
    description: "Calm, affectionate, and loyal. Bernese Mountain Dogs are excellent family companions.",
    traits: {
      energy_level: "medium",
      size: "large",
      grooming_needs: "moderate",
      good_with_children: true,
      good_with_pets: true,
      hypoallergenic: false,
      apartment_friendly: false,
      experience_needed: "intermediate",
      temperament: ["calm", "affectionate", "loyal"],
    },
    care_info: {
      exercise_needs: "Moderate daily exercise and regular walks",
      grooming_tips: "Brush 2-3 times per week, more during shedding",
      health_considerations: "Hip dysplasia, cancer, and bloat",
    },
  },
  {
    id: "corgi",
    name: "Pembroke Welsh Corgi",
    image: "https://images.dog.ceo/breeds/corgi-cardigan/n02113186_1031.jpg",
    description: "Intelligent, affectionate, and alert. Corgis are known for their short legs and big personality.",
    traits: {
      energy_level: "high",
      size: "small",
      grooming_needs: "moderate",
      good_with_children: true,
      good_with_pets: true,
      hypoallergenic: false,
      apartment_friendly: true,
      experience_needed: "beginner",
      temperament: ["intelligent", "affectionate", "alert"],
    },
    care_info: {
      exercise_needs: "Daily exercise and mental stimulation required",
      grooming_tips: "Brush 2-3 times per week, more during shedding",
      health_considerations: "Hip dysplasia, eye conditions, and degenerative myelopathy",
    },
  },
  {
    id: "australian_shepherd",
    name: "Australian Shepherd",
    image: "https://images.dog.ceo/breeds/australian-shepherd/pepper.jpg",
    description: "Intelligent, energetic, and loyal. Australian Shepherds are excellent working dogs and family companions.",
    traits: {
      energy_level: "high",
      size: "medium",
      grooming_needs: "moderate",
      good_with_children: true,
      good_with_pets: true,
      hypoallergenic: false,
      apartment_friendly: false,
      experience_needed: "intermediate",
      temperament: ["intelligent", "energetic", "loyal"],
    },
    care_info: {
      exercise_needs: "High exercise and mental stimulation requirements",
      grooming_tips: "Brush 2-3 times per week, more during shedding",
      health_considerations: "Hip dysplasia, eye conditions, and epilepsy",
    },
  }
]
